### ISSUE TITLE
I could't visit the doc

### ISSUE THREAD

**Issue by lwsys** [Codpoe/servite#1]
When I visit the servite docs using firefox or chrome, I get the error "An error occurred during a connection to servite.vercel.app. PR_CONNECT_RESET_ERROR". Then I use mobile phone to try,but I received the TIME_OUT. So could you give me some way to visit the doc please?

**Comment by Codpoe** [comment]
这可能是 vercel 被墙了吧，可以挂个小梯子访问，或者我看下能不能部署一份在 github

**Comment by Codpoe** [comment]
部署在 GitHub Pages 了，可以试下访问这个地址：https://codpoe.github.io/servite/
